### PR TITLE
fix types missing in ESM monorepos

### LINKED ISSUE #319: ESM monorepo fails to find types declaration
### Description

Somehow Typescript can't find the type declarations when using ``type: module`` in package.json

When I remove ``type: module``, it works fine.

```js
// tsconfig.json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "Node16",
    "moduleResolution":"Node16",
    "outDir": "./dist",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "skipLibCheck": true,
    "rootDir": "./src",
    "baseUrl": ".",
    "paths": {
      "#api/*": ["./src/*"]
    }
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts"],
}
```

Importing like:
```js
import rateLimit from 'express-rate-limit'
```
Got the error:
```
Could not find a declaration file for module 'express-rate-limit'. 'C:/projects/x/node_modules/.pnpm/express-rate-limit@6.5.1_express@4.18.1/node_modules/express-rate-limit/dist/index.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/express-rate-limit` if it exists or add a new declaration (.d.ts) file containing `declare module 'express-rate-limit';`ts(7016)
```

What am I doing wrong?

### pnpm version

7.9.3

### Library version

6.5.1

### Node version

16.15.0

### Typescript version (if you are using it)

4.7.4

### Module system

ESM

### PR DESCRIPTION
**Pull request by rafaelpimpa**
## Related Issues

- Fixes #319 

## What Does This PR Do?

Fixes types missing in ESM monorepos

### Added

Add ``types`` to module exports: https://nodejs.org/api/packages.html#community-conditions-definitions

## Checklist

- [x] The issues that this PR fixes/closes have been mentioned above.
- [x] What this PR adds/changes/removes has been explained.
- [x] All tests (`npm test`) pass.
- [x] All added/modified code has been commented, and
      methods/classes/constants/types have been annotated with TSDoc comments.
- [x] If a new feature has been added or a bug has been fixed, tests have been
      added for the same.

### CODE REVIEW

**Comment by nfriedly** [comment]
Aaah, interesting. I didn't know about that. Thanks!

**Comment by nfriedly** [comment]
This is now live on npm in v6.5.2 - thanks again!

**Comment by rafaelpimpa** [comment]
worked like a charm, thanks!

**Comment by gamemaker1** [comment]
Sorry I didn't get time to investigate this issue, and thanks for sending in this fix @rafaelpimpa!

**Pull request merged**
