### PR TITLE
Passing current limit as part of rateLimit payload

### PR DESCRIPTION
**Pull request by raghu12133**
Current limit helps to do deep analysis in sudden spike of request in the handler.

### CODE REVIEW

**Comment by nfriedly** [comment]
Cool, this looks smart.

To make the build pass, can you switch it to ES5 syntax (`current: current`)?

**Comment by raghu12133** [comment]
sure

**Comment by raghu12133** [comment]
@nfriedly I have pushed the changes. And any ETA when this will be released?

**Comment by nfriedly** [comment]
It just went live -  v2.7.0

**Comment by raghu12133** [comment]
Cool. Thanks :)

**Pull request merged**
