### PR TITLE
Feature events

### PR DESCRIPTION
**Pull request by tspoke**
Hi,

I needed an event to log infos when an user reach the limit and I didn't want to override default handler method only for that. This PR add a function to this use-case.

Thanks !

### CODE REVIEW

**Comment by nfriedly** [comment]
Hi @tspoke,

Thanks! 

I see what you're going for, but I'm a little bit iffy about the implementation, because I feel like it could cause some confusion.  

What would you say to making the default function accessible, and then to logging would look something like this?

```js
var RateLimit = require('express-rate-limit');

var limiter = new RateLimit({
  handler: function(req, res, next) {
    console.log('limit reached');
    return limiter.defaultHandler(req, res, next);
  }
});
```
Actually, I'm not sure I really like that API either now that I'm looking at it... 

I don't know, do you have any ideas here?

**Comment by tspoke** [comment]
Hi @nfriedly ,

Thank you for your fast answer !

I understand your point about my implementation. 

You solution is interesting but I think it's important to make the difference between the `handler()` method and the potential observers attached to it. In your example you link together the event and the effect into one function. Adding `onLimitReached` as another attribute split the two behaviors.

Your call about this, I can change the PR to match your solution ;)

**Comment by nfriedly** [comment]
Yea... lets ship it like this and see what happens. I have some plans to do a bit of simplification for v3, so if we come up with any better ideas, we can try them out there.

**Comment by nfriedly** [comment]
Should be released as v2.8 once it passes CI

**Comment by tspoke** [comment]
Thank you @nfriedly !

**Pull request merged**
