### PR TITLE
first draft for the types for express rate limiter

### PR DESCRIPTION
**Pull request by andreGarvin**
I think this needs to be improved more, if anyone wants to review the PR and check it out their local branch that would be great

### CODE REVIEW

**Comment by nfriedly** [comment]
This looks good to me. Is there an automated way to ensure it stays in sync with the actual JavaScript files?

**Comment by santiq** [comment]
@nfriedly 
> This looks good to me. Is there an automated way to ensure it stays in sync with the actual JavaScript files?
I think there is no way to do that if the source code is not written in typescript.

Regardless that minor issue, I think this it's a nice feature for those using typescript like me, would you considerer on merging this?

**Comment by nfriedly** [comment]
Fair enough, I'll go ahead and get it merged in and released shortly

**Comment by santiq** [comment]
@nfriedly Thank you so much! 😄

**Pull request merged**
