### PR TITLE
meta: run ci on node 18

### PR DESCRIPTION
**Pull request by gamemaker1**
## Related Issues

--

### Added

- Runs Lint and Publish steps of CI on Node 18.
- Added Node 18 to version matrix for Test steps too.

## Caveats/Problems/Issues

--

## Checklist

- [ ] The issues that this PR fixes/closes have been mentioned above.
- [x] What this PR adds/changes/removes has been explained.
- [x] All tests (`npm test`) pass.
- [ ] All added/modified code has been commented, and
      methods/classes/constants/types have been annotated with TSDoc comments.
- [ ] If a new feature has been added or a bug has been fixed, tests have been
      added for the same.

### CODE REVIEW

**Comment by gamemaker1** [comment]
@nfriedly should we stop running tests on Node 12? (EOL for Node 12 is [April 30th](https://github.com/nodejs/Release#release-schedule), 6 days from now)

**Comment by nfriedly** [comment]
I like adding 18 to the list, but I'd prefer to keep 12 unless there's some incompatibility with a feature that we (or, more likely, one of our dependencies) needs.

I think we could drop 15 and 17, though. Neither are LTS releases, and I find it unlikely that we'd hit any issue in on of those that isn't also in 14, 16, or 18. I generally like to test against a variety of LTS releases, + whatever the current release is.

**Comment by gamemaker1** [comment]
Sounds good, I'll keep 12 but drop 15 and 17 then

**Review by nfriedly — APPROVED** [review]
Approving now based on our conversation; I'm going to be out most of the rest of the day.

**Comment by gamemaker1** [comment]
Thanks, have a good day :D

**Pull request merged**
