### PR TITLE
Make it possible to clear the memory store interval

### PR DESCRIPTION
**Pull request by samshull**

### CODE REVIEW

**Comment by nfriedly** [comment]
Hi @samshull,

Can I ask what the need / reasoning is behind this?

**Comment by samshull** [comment]
@nfriedly When performing an integration test against an app that uses this middleware, the process is left open because the interval cannot be cleared. Currently, the only way to work around that is `process.exit()`. This would allow the interval to be cleaned up without forcing the process to end.

**Comment by nfriedly** [comment]
Aah, that's a fair point. Although, I think the correct solution is to use https://nodejs.org/api/timers.html#timers_timeout_unref - setTimeout(...).unref();

Can you update the PR with that?

**Comment by samshull** [comment]
@nfriedly updated, and I agree much more elegant

**Comment by samshull** [comment]
This needs to be published, please.

**Comment by nfriedly** [comment]
Doh, sorry. I think I did the merge on my phone. Should be out in `v2.5.0` once the CI loop finishes.

**Pull request merged**
