### PR TITLE
feat: add named export for memory store

### LINKED ISSUE #289: Expose `MemoryStore` as a named export
### Description

I want to be able to toggle between using a custom third-party store and the "default" memory one. 
Based on https://github.com/nfriedly/express-rate-limit#store you can write your own. I don't want to do that. I want to use the in-memory "default" one from this package. 
E.g. 
```js
export default rateLimit({
   ...
  store: REDIS_URL
    ? new RedisStore(REDIS_STUFF)
    : new Memory(),
})

```
You can't do
```js
import rateLimit, {MemoryStore} from 'express-rate-limit'
```
because the only thing exported is the `rateLimit` default function. 

My only way to do this now is to copy-n-paste the source code from https://github.com/nfriedly/express-rate-limit/blob/master/source/memory-store.ts into my project. 

### Why

To avoid the copy-n-paste and then have to rewrite it if the API changes. 

### Alternatives

Mentioned above .

### PR DESCRIPTION
**Pull request by gamemaker1**
## Related Issues

- Closes #289

### Added

- Added a named export for the `MemoryStore` class.

## Checklist

- [x] The issues that this PR fixes/closes have been mentioned above.
- [x] What this PR adds/changes/removes has been explained.
- [x] All tests (`npm test`) pass.
- [x] All added/modified code has been commented, and
      methods/classes/constants/types have been annotated with TSDoc comments.
- [x] If a new feature has been added or a bug has been fixed, tests have been
      added for the same.

### CODE REVIEW

**Review by nfriedly — APPROVED** [review]
LGTM!

That esbuild `--footer` is getting a little hairy, but I don't think there's a better option right now.

**Comment by gamemaker1** [comment]
> That esbuild --footer is getting a little hairy, but I don't think there's a better option right now.

That's bugging me too 😬. Maybe we can use  esbuild's `__toCommonJSExport` function there instead of the `module.export.{default, rateLimit,Memory store}`?

**Comment by nfriedly** [comment]
Yeah...  ideally I'd like to see a new flag in ES build that controls the default export behavior for cjs, rather than us having to continue hacking around it.

**Comment by gamemaker1** [comment]
> Maybe we can use ESBuild's `__toCommonJSExport` function there instead of the `module.export.{default, rateLimit,Memory store}`

That didn't work - Jest could not resolve named imports in the JS-ESM import tests when I did that. Merging with the big footer for now.

**Comment by gamemaker1** [comment]
Should I release v6.2.0 - it will include this as well as the deprecate `onLimitReached` fixes.

**Comment by nfriedly** [comment]
Yeah, go ahead :)

**Pull request merged**
