### PR TITLE
Typescript rebase

### PR DESCRIPTION
**Pull request by shilangyu**
In response to #138 ([this](https://github.com/nfriedly/express-rate-limit/issues/138#issuecomment-633145625) to be exact) I have ported the new changes from master to typescript branch. Most of them required just copy paste.

Some tests are failing (which they already have been doing on a clean install), I have not yet investigated why, thus I'm leaving the PR on a draft status for now.

TODO:
- [x] fix failing tests
- [ ] bump dependencies to match master
- [x] rebase new changes

### CODE REVIEW

**Comment by nfriedly** [comment]
This is awesome! I have to apologise, I just merged in #190 which has a lot of indentation changes. If it doesn't rebasr easily, there is a way to do it that ignores whitespace changes. Let me know if you end up wanting help there.

**Comment by shilangyu** [comment]
No worries, if it doesn't rebase I'll port the changes manually. Yes I need help with explaining if it's normal that some tests are failing on the typescript branch (even before I ported the changes).

**Comment by nfriedly** [comment]
Yea, I was hoping someone else would know more about that, I think all of the tests should pass.

**Comment by shilangyu** [comment]
Just letting you know I have not forgotten about this, I just have finals around the corner and don't have free time ATM

**Comment by nfriedly** [comment]
No worries, good luck with your finals!

**Comment by shilangyu** [comment]
Ok the tests are not failing. Apparently there is a problem with `npm test` (thus Mocha?) on Windows. There, the tests fail randomly. Meaning there are some race conditions happening in the tests which I am unable to find because I don't know how Mocha works under the hood. It would be nice if someone could confirm this behavior on a Windows machine. It might be something worth looking into, to make sure the tests are failing due to Mocha and not the implementation of express-rate-limit (which does not use any OS specific APIs so it's unlikely).

So apart from that, I can rebase the changes and bump dependencies.

**Comment by nfriedly** [comment]
Oh, ugh, yea, I think I do remember problems with testing on windows. I think I tried to fix it like a year ago and didn't figure it out. I'm sorry. I'll try to give it another shot sometime soon.

**Comment by shilangyu** [comment]
Manually rebased changes and bumped dependencies. Everything should be working and up to date now :)

**Comment by nfriedly** [comment]
Awesome work, thank you!

**Pull request merged**
