### PR TITLE
feat: setHeader function

### PR DESCRIPTION
**Pull request by ekoeryanto**
It allows me to use this plugin with fastify fastify/fastify-rate-limit#10

### CODE REVIEW

**Comment by nfriedly** [comment]
Hi,

I'm not quite sure I understand the goal here, does express-rate-limit not work with fastify right now?

And then I also see a couple of issues with the implementation:

* the big one is that you defined `options.setHeaders` as expecting `req, res`, but then you're calling it with two strings (?)
* also, it's failing the linter; `npx eslint . --fix` should be able to fix that automatically

**Comment by ekoeryanto** [comment]
Sorry for that, I edited directly on github web ui. I'll be back when I am not AFK

**Comment by nfriedly** [comment]
FYI, res.setHeader is a core Node.js thing, not something Express ads: https://nodejs.org/api/http.html#http_response_setheader_name_value ;)

**Comment by nfriedly** [comment]
I'm going to go ahead and close this for now. Feel free to re-open if appropriate.

**Pull request closed without merging**
